services:
  web:
    build: .
    container_name: deno-container
    environment:
      - USER_NAME=<USER_NAME>
      - PASSWORD=<PASSWORD>
      - DENO_KV_ACCESS_TOKEN=<DENO_KV_ACCESS_TOKEN>
      - KV_PATH=<KV_PATH>
    ports:
      - "8000:8000"
